[package]
name = "wasm-parser"
version = "0.1.0"
authors = ["SamGinzburg <ginzburg.sam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wast = "24.0.0"
regex = "1"
lazy_static = "1.4.0"
ocl = "0.19"
wasi-common = "0.20.0"
wasmtime-wasi = "0.20.0"
wasmtime = "0.20.0"
crossbeam = "0.8.0"
rayon = "1.5"
wiggle = "0.20.0"
byteorder = "1.3.4"
wasmtime-wiggle = "0.20.0"

