[package]
name = "rust-pdfwriter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#pdf-writer = "0.6"
pdf-writer = { path = "/home/ginzburgsam/pdf-writer" }
